### ISSUE TITLE
Tooltip zIndex not working 

### ISSUE THREAD

**Issue by akashishu777** [xuopled/react-simple-tooltip#12]
https://xuopled.github.io/react-simple-tooltip/

Try changing your zIndex it is expected that the tooltip get visible over 
the text is written.
```
</ReactSimpleTooltip>
</ReactSimpleTooltip>

```
but it is not.

**Comment by cedricdelpoux** [comment]
Hello @akashishu777. Thank you for reporting this issue. 
I fixed the issue and published the `v2.3.3` release.

Feel free to reopen if you still have the problem.
