### ISSUE TITLE
Request: configure tooltip width

### ISSUE THREAD

**Issue by torresdiego** [xuopled/react-simple-tooltip#14]
It would be nice to have a "width" Prop, actually If I have a long content, it displays two or three words per line and the div gets tall... Thanks.

<img width="69" alt="react-tooltip" src="https://user-images.githubusercontent.com/2292825/49020869-330e3380-f170-11e8-8065-cf28075b7abc.PNG">

**Comment by cedricdelpoux** [comment]
Hi @torresdiego, could you try wrapping your content with a react element and limit width on it ?

**Comment by torresdiego** [comment]
> Hi @torresdiego, could you try wrapping your content with a react element and limit width on it ?

I couldn't get it to work, I tried to assign the "content" property to a custom made component (with a styled<div> inside). For now, I'm playing with Bubble's css class to give it a fixed size.

**Comment by cedricdelpoux** [comment]
Nice move

**Comment by vedran-maricevic** [comment]
I am having a same requirements. If I have some long message, I would like to display it in one liner, or at least 2 lines. @torresdiego  could you please show me how you did that width trick?

Thank you

**Comment by cedricdelpoux** [comment]
use the `content` prop to pass a component with styles and style it with `white-space: nowrap`

**Comment by properCase** [comment]
Would adding an optional width parameter which did this for you be an option?  ie, either pass in the component, etc... or just use `width={150}` and it sets the width to 150px.  The whole reason I started looking at this is because I'm looking for the least amount of work on a tooltip possible. :)

**Comment by cedricdelpoux** [comment]
why not using the `content` prop ?

**Comment by MuneebBashir111** [comment]
I solved it like this......
<ReactSimpleTooltip 
                        arrow={0}
                        background="linear-gradient(#2593C5,#000000)"
                        border="#000"
                        color="#fff"
                        content={"back-tick"Module not found: 
Can't resolve 'styled-component']"back-tick"} 
                        fadeDuration={0}
                        fadeEasing="linear"
                        fixed={false}
                        fontFamily="inherit"
                        fontSize="inherit"
                        offset={0}
                        padding={16}
                        placement="top"
                        radius={0}
                        zIndex={1}
                        style={{whiteSpace:'pre'}}
                        >
