### ISSUE TITLE
Warning prop type `string` to Wrapper and Bubble

### ISSUE THREAD

**Issue by 1898182** [xuopled/react-simple-tooltip#41]
Warning: Failed prop type: Invalid prop `radius` of type `string` supplied to `Tooltip.Bubble`, expected `number`. -> index.js:1
---

When using the tooltip and applying a `radius` of 5, I suppose you send the information to your Bubble and Wrapper components but they require a number when it receives a string instead and it gives a warning. The tooltip works fine though.

Also, when importing react-simple-tooltip, I got a message asking me to `npm install @types/react-simple-tooltip` if a **.d.ts** file was present. I got rid of the message by creating **react-simple-tooltip.d.ts** in the **lib** folder and inserted `declare module 'react-simple-tooltip';` in it. I'm not familiar with modules and open source projects so I prefer to tell you instead of creating a pull request.

**Comment by cedricdelpoux** [comment]
Thank you for reporting this. I fixed the radius proptype. 
I never use Typescript so I'm not sure how to declare a definition file but I added one in src. For now it's not publish. PR are welcomes if you want to contribute
