### ISSUE TITLE
dont work in Firefox

### ISSUE THREAD

**Issue by frostspb** [xuopled/react-simple-tooltip#9]
Hi. Thank for u lib. I have problem. In firefox 58 tooltips dont work. package version 2.3.0

**Comment by cedricdelpoux** [comment]
@frostspb Thank you for reporting this. I will investigate

**Comment by cedricdelpoux** [comment]
@frostspb What do you mean by it do not work ?

I just tried and it work for me
<img width="796" alt="screen shot 2018-03-13 at 09 29 28" src="https://user-images.githubusercontent.com/2683300/37330374-22eb29da-26a1-11e8-8d5d-2669d3967a07.png">

**Comment by frostspb** [comment]
Hi.
Here is my code. Tooltip works in Chrome, but is not shown in Firefox

```
import React from 'react';
import { Button} from 'reactstrap';
import Tooltip from "react-simple-tooltip"
import { InputGroup } from 'reactstrap';

export const OrdISToolBtn = ({ click_func, glyph, hint }) => (
    <InputGroup >
        <Button color="black" onClick={click_func} ><Tooltip content={hint}>{glyph} </Tooltip></Button>
    </InputGroup>
)
```

**Comment by cedricdelpoux** [comment]
Your syntax dos not fallow the README. Try with this please:

```
<Tooltip content={hint}>
    <Button color="black" onClick={click_func} >{glyph}</Button>
  </Tooltip>
```

**Comment by frostspb** [comment]
Its work! Thank you!
